AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Security Layer: Deploys Security Groups for Web and Database tiers.
  Depends on the VPC/Network stack being deployed first.

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Name of the environment #must match VPC stack


#security testing
#Resources:
# TestBucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: !Sub "${EnvironmentName}-checkov-test-bucket"
#      AccessControl: PublicRead # This is a major security violation
